language: node_js
node_js:
- node
cache: npm
script:
- "./bin/run --version"
- "./bin/run --help"
- npm run test
after_success:
- "./node_modules/.bin/nyc report --reporter text-lcov > coverage.lcov"
- bash < (curl -s https://codecov.io/bash)
deploy:
  provider: npm
  on:
    tags: true
  skip_cleanup: true
  email: kremenh@gmail.com
  api_key:
    secure: cmHzoQVoOy5s1Y9nxZUZSYMn582Hxn5ZmJ4pKbNoSmzVod8QJu4nTVWbj5DEfKSB43wJNII9JnFRmGaoo5F4gRy47BdpQAbbXCUIAkM6vsAvd9XTT4Kxcjkhzd2jH5oNikklCxPQthnLpnCBZHnXKSzmpfzoWhZ9aK2xyUGk5Q+Yb3Du300GHLcaTvaC7zMzi62CTTIrNi+GTKHVQeihft+FZeOM1Kneo3KN0p+nbuMsguPrWRTH5bSlIKYpgJ5FwJtZhIko+nNkjR5oXGXbG0SBg73nCrFTMZWGBRtZ8fnCwb0j7aWbrshZJcG6cURflPGvekmKB7tDktU/1uF0BQFpZAmwj6qR6oDLiokwOSS/1XDJwVt1UJXYbt9Xv6Yt9+i6CzgBiipQvIDY/3OejKUPiIaq7WqI8SwL+JLKgyhXHQKgLT2bAEgXGiyqYkrKCZUaak73VGU64eMgFHByj6bO5ZiWXYk63W5FCUnDAZQGPLpYYrnuanlANSowgdC1y7EGb0I0mTQ0TwNXA5d9bheRAOvj1L1OKSzO4KZi4LzQy+Wh++uz+9keJBZUz51W5rJD0sDGTx0Hm7PgveLkAJgtWiC3lu4k+W34oi8SWbd68ccC3zfj32jOPc7lW0OgxH4pOcCQHk3Jlm/QcsEpIoTXArJIaG7lEMozF4A9l0M=
